[package]
name = "vecto-rs"
version = "3.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["maths"]

[dependencies]
bytemuck = {version = "1.22.0", optional = true}
num-traits = "0.2.19"

[features]
bytemuck = ["dep:bytemuck"]